vim.opt.runtimepath:prepend("~/.bonktemp/")
require "user.bonkyfuncs"
require "user.bonky-autocmds"
require "user.options"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.neoscroll"
require "user.image-nvim"
require "user.nvim-tree"
require "user.lualine"
require "user.treesitter"
require "user.pounce_conf"
--require "user.sessionreload"
--require "user.key-menu"
require "user.gitsigns"
require "user.keymaps"
--require "user.neo-img"
require "user.guess-indent"
--require "user.registers"
--require "user.lsp"
require "user.lang"
require "user.misc"
require "user.telescope_bonky"
require("hardtime").setup()
require("nvim-autopairs").setup()
